# Continuous Integration
name: Build

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - main
    - develop

permissions:
  checks: write

jobs:
  build:

    name: Build
    runs-on: ubuntu-latest

    steps:

    # ================================
    # SHALLOW CLONE
    # ================================
    - name: Shallow clone
      uses: actions/checkout@v4

    # ================================
    # UPDATE CONFIGURE SCRIPTS
    # ================================
    - name: Update configure scripts
      run: |
        autoreconf --install
        ./configure

    # ================================
    # MAKE ALL
    # ================================
    - name: Make all
      run: make all

    # ================================
    # TEST
    # ================================
    - name: Test
      run: make tests

    # ================================
    # COVERAGE
    # ================================
    - name: Coverage
      run: make coverage

    # ================================
    # UPLOAD COVERAGE REPORTS TO CODECOV
    # ================================
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: guillermocalvo/exceptions4c

    # ================================
    # TEST REPORT
    # ================================
    - name: Generate test report
      uses: guillermocalvo/autotools-test-report@v1
      if: success() || failure()

    # ================================
    # UPLOAD TEST LOG
    # ================================
    - name: Upload test report as artifact
      uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        path: ${{github.workspace}}/test-suite.log
